### ISSUE TITLE
AttributeError: exclude_context

### ISSUE THREAD

**Issue by micmord** [RedTurtle/redturtle.portlet.collection#5]
Upgrading Plone from 4.3.3 to 4.3.4 and redturtle.portlet.collection from 0.4 to 0.5 olds portlet crash:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.portlets.browser.formhelper, line 126, in __call__
  Module zope.formlib.form, line 795, in __call__
  Module five.formlib.formbase, line 50, in update
  Module zope.formlib.form, line 758, in update
  Module zope.formlib.form, line 833, in setUpWidgets
  Module zope.formlib.form, line 412, in setUpEditWidgets
  Module zope.schema._bootstrapfields, line 215, in get
AttributeError: exclude_context

No problem with new portlets.

**Comment by keul** [comment]
See https://github.com/RedTurtle/redturtle.portlet.collection/issues/4

**Comment by keul** [comment]
Ok... the issue is still this: https://github.com/plone/plone.portlet.collection/issues/5

We can't fix this here because is a Plone bug. You must pin plone.portlet.collection 2.1.7 where the bug I submitted

**Comment by micmord** [comment]
I confirm that with https://pypi.python.org/pypi/plone.portlet.collection/2.1.7 all works fine!
Thank you :8ball:
